# Generated by Django 2.2 on 2020-07-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='описание')),
                ('category', models.CharField(choices=[('other', 'Разное'), ('food', 'Продукты питание'), ('household', 'Хоз.товары'), ('toys', 'Детские игрушки'), ('electronics', 'Бытовая техника')], default='other', max_length=20, verbose_name='категория')),
                ('amount', models.IntegerField(verbose_name='остаток')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='цена')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
